import { Injectable } from '@angular/core';
import { Subject, Observable } from 'rxjs';

export interface RetirementProofInputs {
  creditId: string;
  creditSecret: string;
  creditHash: string;
  vintageYear: number;
  methodologyCode: number;
  permanenceRating: number;
  tonneVolume: number;
  merklePath: string[];
  merkleIndices: number[];
  // Public inputs
  nullifier: string;
  registryMerkleRoot: string;
  minVintageYear: number;
  minPermanence: number;
  volumeCommitment: string;
  corridorId: string;
}

export interface RetirementProof {
  proof: string;
  publicInputs: {
    nullifier: string;
    registryMerkleRoot: string;
    volumeCommitment: string;
    corridorId: string;
    minVintageYear: number;
    minPermanence: number;
  };
  generationTimeMs: number;
}

export interface ComplianceProofInputs {
  retirementNullifiers: string[];
  retirementVolumes: number[];
  activeCount: number;
  companySecret: string;
  commitmentThreshold: number;
  periodId: string;
  complianceNullifier: string;
  nullifierSetRoot: string;
}

export interface ComplianceProof {
  proof: string;
  publicInputs: Record<string, string>;
  generationTimeMs: number;
}

export interface ProofProgress {
  stage: 'witness' | 'proof';
  percent: number;
}

@Injectable({ providedIn: 'root' })
export class NoirService {
  private ready = false;
  private noirModule: any = null;
  private bbModule: any = null;
  private retirementCircuit: any = null;
  private complianceCircuit: any = null;

  private progressSubject = new Subject<ProofProgress>();
  proofProgress$: Observable<ProofProgress> = this.progressSubject.asObservable();

  isReady(): boolean {
    return this.ready;
  }

  async initialize(): Promise<void> {
    if (this.ready) return;

    try {
      // Dynamically import WASM modules (lazy — heavy bundles)
      const [noirJs, bbJs] = await Promise.all([
        import('@noir-lang/noir_js'),
        import('@aztec/bb.js'),
      ]);
      this.noirModule = noirJs;
      this.bbModule = bbJs;

      // Load compiled circuit JSON from assets
      // In production these are generated by `nargo compile` and copied to assets/circuits/
      try {
        const retirementRes = await fetch('/assets/circuits/retirement_proof.json');
        this.retirementCircuit = retirementRes.ok ? await retirementRes.json() : null;

        const complianceRes = await fetch('/assets/circuits/compliance_proof.json');
        this.complianceCircuit = complianceRes.ok ? await complianceRes.json() : null;
      } catch {
        // Circuit JSON not available yet — run in simulation mode
      }

      this.ready = true;
    } catch (err) {
      console.warn('Noir WASM not available, running in simulation mode:', err);
      // Mark ready anyway — simulation mode will be used
      this.ready = true;
    }
  }

  async generateRetirementProof(inputs: RetirementProofInputs): Promise<RetirementProof> {
    await this.initialize();
    const start = Date.now();

    // Attempt real proof generation if circuit + WASM available
    if (this.noirModule && this.bbModule && this.retirementCircuit) {
      try {
        return await this.generateRealRetirementProof(inputs, start);
      } catch (err) {
        console.warn('Real proof generation failed, falling back to simulation:', err);
      }
    }

    // Simulation mode: emit progress and return deterministic mock proof
    return this.simulateRetirementProof(inputs, start);
  }

  async generateComplianceProof(inputs: ComplianceProofInputs): Promise<ComplianceProof> {
    await this.initialize();
    const start = Date.now();

    if (this.noirModule && this.bbModule && this.complianceCircuit) {
      try {
        const { Noir } = this.noirModule;
        const { UltraHonkBackend } = this.bbModule;

        this.progressSubject.next({ stage: 'witness', percent: 20 });
        const noir = new Noir(this.complianceCircuit);
        const bb = new UltraHonkBackend(this.complianceCircuit.bytecode);

        const noirInputs = this.mapComplianceInputs(inputs);
        const { witness } = await noir.execute(noirInputs);
        this.progressSubject.next({ stage: 'proof', percent: 50 });

        const { proof, publicInputs } = await bb.generateProof(witness);
        this.progressSubject.next({ stage: 'proof', percent: 100 });

        return {
          proof: '0x' + Buffer.from(proof).toString('hex'),
          publicInputs: {},
          generationTimeMs: Date.now() - start,
        };
      } catch {
        // fall through to simulation
      }
    }

    await this.delay(800);
    return {
      proof: '0x' + '00'.repeat(64),
      publicInputs: {},
      generationTimeMs: Date.now() - start,
    };
  }

  private async generateRealRetirementProof(
    inputs: RetirementProofInputs,
    start: number,
  ): Promise<RetirementProof> {
    const { Noir } = this.noirModule;
    const { UltraHonkBackend } = this.bbModule;

    this.progressSubject.next({ stage: 'witness', percent: 10 });
    const noir = new Noir(this.retirementCircuit);
    const bb = new UltraHonkBackend(this.retirementCircuit.bytecode);

    const noirInputs = this.mapRetirementInputs(inputs);
    this.progressSubject.next({ stage: 'witness', percent: 40 });

    const { witness } = await noir.execute(noirInputs);
    this.progressSubject.next({ stage: 'proof', percent: 10 });

    const { proof } = await bb.generateProof(witness);
    this.progressSubject.next({ stage: 'proof', percent: 100 });

    return {
      proof: '0x' + Buffer.from(proof).toString('hex'),
      publicInputs: {
        nullifier: inputs.nullifier,
        registryMerkleRoot: inputs.registryMerkleRoot,
        volumeCommitment: inputs.volumeCommitment,
        corridorId: inputs.corridorId,
        minVintageYear: inputs.minVintageYear,
        minPermanence: inputs.minPermanence,
      },
      generationTimeMs: Date.now() - start,
    };
  }

  private async simulateRetirementProof(
    inputs: RetirementProofInputs,
    start: number,
  ): Promise<RetirementProof> {
    // Realistic simulation: emit progress over ~3 seconds
    this.progressSubject.next({ stage: 'witness', percent: 0 });
    await this.delay(400);
    this.progressSubject.next({ stage: 'witness', percent: 30 });
    await this.delay(400);
    this.progressSubject.next({ stage: 'witness', percent: 100 });
    await this.delay(200);
    this.progressSubject.next({ stage: 'proof', percent: 0 });
    await this.delay(600);
    this.progressSubject.next({ stage: 'proof', percent: 50 });
    await this.delay(800);
    this.progressSubject.next({ stage: 'proof', percent: 100 });

    const mockNullifier = inputs.nullifier || ('0x' + this.pseudoHash(inputs.creditId + inputs.corridorId));

    return {
      proof: '0x' + 'ab'.repeat(64),
      publicInputs: {
        nullifier: mockNullifier,
        registryMerkleRoot: inputs.registryMerkleRoot || '0x' + '01'.repeat(32),
        volumeCommitment: inputs.volumeCommitment || '0x' + '02'.repeat(32),
        corridorId: inputs.corridorId || '0x' + '03'.repeat(32),
        minVintageYear: inputs.minVintageYear,
        minPermanence: inputs.minPermanence,
      },
      generationTimeMs: Date.now() - start,
    };
  }

  private mapRetirementInputs(inputs: RetirementProofInputs): Record<string, any> {
    return {
      credit_id: inputs.creditId,
      credit_secret: inputs.creditSecret,
      credit_hash: inputs.creditHash,
      vintage_year: inputs.vintageYear,
      methodology_code: inputs.methodologyCode,
      permanence_rating: inputs.permanenceRating,
      tonne_volume: inputs.tonneVolume,
      merkle_path: inputs.merklePath,
      merkle_indices: inputs.merkleIndices,
      nullifier: inputs.nullifier,
      registry_merkle_root: inputs.registryMerkleRoot,
      min_vintage_year: inputs.minVintageYear,
      min_permanence: inputs.minPermanence,
      volume_commitment: inputs.volumeCommitment,
      corridor_id: inputs.corridorId,
    };
  }

  private mapComplianceInputs(inputs: ComplianceProofInputs): Record<string, any> {
    return {
      retirement_nullifiers: inputs.retirementNullifiers,
      retirement_volumes: inputs.retirementVolumes,
      active_count: inputs.activeCount,
      company_secret: inputs.companySecret,
      commitment_threshold: inputs.commitmentThreshold,
      period_id: inputs.periodId,
      compliance_nullifier: inputs.complianceNullifier,
      nullifier_set_root: inputs.nullifierSetRoot,
    };
  }

  /** Deterministic pseudo-hash for mock nullifiers (dev only) */
  private pseudoHash(input: string): string {
    let h = 0x811c9dc5;
    for (let i = 0; i < input.length; i++) {
      h ^= input.charCodeAt(i);
      h = (h * 0x01000193) >>> 0;
    }
    return h.toString(16).padStart(8, '0').repeat(8);
  }

  private delay(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
}
